### ISSUE TITLE
mycroft.conf companion changes

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-i2csound#7]
if a mk2 is detected, ovos-shell companion gui extension needs to be set in mycroft.conf gui section

**Comment by builderjer** [comment]
This is out of the scope of i2csound as it runs well before any OVOS services are started.

Instead, I create a file to be read with the detection results stored there.  This should help with PHAL validation for the specific plugins.

Changes made [here](https://github.com/OpenVoiceOS/ovos-i2csound/pull/9)

Please make any further comments on that PR
